version: "2"
services:

  #Plex

  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK_SET=022 #optional
      - PLEX_CLAIM= #optional
    volumes:
      - /home/leandrensen/Desktop/mediaserver/plex/config:/config
      - /home/leandrensen/Desktop/mediaserver/media/peliculas:/peliculas
      - /home/leandrensen/Desktop/mediaserver/media/series:/series
      - /home/leandrensen/Desktop/mediaserver/media/documentales:/documentales
      - /home/leandrensen/Desktop/mediaserver/media/anime:/anime
      - /home/leandrensen/Desktop/mediaserver/media/musica:/musica
    restart: unless-stopped
  tautulli:
    image: linuxserver/tautulli
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - /home/leandrensen/Desktop/mediaserver/tautulli/config:/config
      - /home/leandrensen/Desktop/mediaserver/plex/config/Library/Application\ Support/Plex\ Media\ Server/Logs:/logs:ro
    ports:
      - 8181:8181
    restart: unless-stopped

  #Searchers 

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires
      - UMASK_SET=022 #optional
    volumes:
      - /home/leandrensen/Desktop/mediaserver/sonarr/config:/config
      - /home/leandrensen/Desktop/downloads:/downloads 
      - /home/leandrensen/Desktop/mediaserver/media/series:/series
      - /home/leandrensen/Desktop/mediaserver/media/anime:/anime
    ports:
      - 8989:8989
    restart: unless-stopped
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires
      - UMASK_SET=022 #optional 
    volumes:
      - /home/leandrensen/Desktop/mediaserver/radarr/config:/config
      - /home/leandrensen/Desktop/downloads:/downloads 
      - /home/leandrensen/Desktop/mediaserver/media/peliculas:/peliculas
      - /home/leandrensen/Desktop/mediaserver/media/documentales:/documentales 
    ports:
      - 7878:7878
    restart: unless-stopped
  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires
      - UMASK_SET=022 #optional 
    volumes:
      - /home/leandrensen/Desktop/mediaserver/lidarr/config:/config
      - /home/leandrensen/Desktop/downloads:/downloads
      - /home/leandrensen/Desktop/mediaserver/media/musica:/musica
    ports:
      - 8686:8686
    restart: unless-stopped
  
  #Indexers

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires
      - RUN_OPTS=run options here #optional
    volumes:
      - /home/leandrensen/Desktop/mediaserver/jackett/config:/config
      - /home/leandrensen/Desktop/mediaserver/jackett/torrentfiles:/downloads
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 9117:9117
    restart: unless-stopped

  #Downloaders

  deluge:
    image: linuxserver/deluge
    container_name: deluge
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires
      - UMASK_SET=022 #optional
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - /home/leandrensen/Desktop/mediaserver/deluge/config:/config
      - /home/leandrensen/Desktop/downloads:/downloads
      - /home/leandrensen/Desktop/mediaserver/jackett/torrentfiles:/torrentfiles
    ports:
      - 9000:9000
    restart: unless-stopped
